# Generated by Django 4.1.7 on 2023-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
